# Generated by Django 5.0.6 on 2024-07-12 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(choices=[('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years')], max_length=7)),
                ('mobile', models.CharField(max_length=15)),
                ('organization', models.CharField(choices=[('IBM', 'IBM'), ('Edunet', 'Edunet'), ('DGT', 'DGT')], max_length=6)),
                ('division_unit', models.CharField(choices=[('ADIT', 'ADIT'), ('IOT', 'IOT'), ('CSA', 'CSA')], max_length=4)),
                ('private_key', models.CharField(blank=True, max_length=255)),
                ('face_data', models.JSONField(blank=True, default=dict)),
                ('attendance_id', models.CharField(blank=True, max_length=8, unique=True)),
                ('aadhar_id', models.CharField(max_length=12)),
                ('user_picture', models.ImageField(blank=True, null=True, upload_to='user_pictures/')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
